account/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import index, signin

app_name='account'
urlpatterns = [
    path('', views.index),
    path('register/',views.UserRegisterView.as_view(), name='user_register'),
    path('verify/',views.UserRegistrationVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
 ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import account.views
import product.views
import core.views
from product.views import ProductList, products
from account.views import register_view, signin, logout, contact
from core.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'home'), namespace='home')),
    path('account/', include(('account.urls'), namespace='account')),
    path('product/', product.views.products),
    # path('', include('account.urls')),
    path('index', account.views.index),
    path('signin', account.views.signin),
    path('logout', account.views.logout),
    path('about', account.views.about),
    path('login', account.views.register_view),
    path('contact', account.views.contact),
    path('product/list', product.views.ProductList.as_view()),
    path('product/index', account.views.index),
    path('product/signin', account.views.signin),
    path('product/logout', account.views.logout),
    path('product/about', account.views.about),
    path('product/login', account.views.register_view),
    path('product/contact', account.views.contact),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class ="alert alert-{{msg.tags}}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-danger ">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">HOME</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'account:user_logout' %}">Logout</a>
            {% else %}
            <a class="nav-link active" href="{% url 'account:user_register' %}">Register</a>
            <a class="nav-link active" href="{% url 'account:user_login' %}">Login</a>
            {% endif %}
            {% if request.user.is_admin %}
            <a class="nav-link active" href="{% url 'home:home' %}">Bucket</a>
            {% endif%}


        </div>

    </div>
</nav>